name: "Sphinx: Render docs"

on: 
  push:
    branches: ["main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: "3.14"

    - name: Install dependencies
      run: uv sync --group docs --locked
    - name: Build Documentation
      run: uv run --group docs sphinx-build -M html docs/source docs/build

    - uses: actions/upload-artifact@v4
      with:
        name: Documentation
        path: "$GITHUB_WORKSPACE/docs/build/html/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
